# Run through tests/run.sh; each group gets fresh fixtures.
fixture_ma_archive
fixture_acp
section "review turns may read history, never publish or rewrite it"
# The threat model is deliberately "the same as running the agent by hand in the repo":
# it may read the tree and the history. What it may not do is publish or destroy — a
# linked worktree shares the main object store and the REAL remotes, so a `git push` from
# inside a mount reaches production.
GS="$WORK/gitshim"; mkdir -p "$GS"
# Generated by the PRODUCTION function against the REAL git. The previous fixture pasted the
# shim body inline AND pointed it at an echo-only fake, so it could prove which verbs were
# admitted and nothing else — while the shipped shim was defeatable through the environment,
# through exec-taking flags on permitted verbs, and through a ref-writing verb on its own
# allowlist. A fake git cannot observe any of that. (codex + grok, round 7.)
( set -e
  eval "$(awk '/^write_git_shim\(\) \{/,/^\}/' "$REPO/helpers/runphase.sh")"
  write_git_shim "$GS" "$(command -v git)" )
[ -x "$GS/git" ] && ok "the suite builds the shim from the shipped generator" || fail "shim generator not callable"

# The INVARIANT, not an enumeration of known tricks: a mounted review turn must not be able to
# execute an arbitrary program or write a file through git. Refusal and neutralisation are both
# acceptable mechanisms; execution is not. Stating it this way is what the corpus advisory asked
# for — a new trick fails this block without anyone naming it first.
GV="$WORK/gitshim-victim"; mkdir -p "$GV"
git -C "$GV" init -q . >/dev/null 2>&1
printf 'base\n' > "$GV/f.txt"
git -C "$GV" add -A >/dev/null 2>&1
git -C "$GV" -c user.email=t@t -c user.name=t commit -q -m base >/dev/null 2>&1
# EVERY payload destination lives INSIDE the scanned root. The previous fixture put the
# canary and the --output target in $WORK while the scan covered $GV and an unused
# $WORK/gitshim-out, so eight of the twelve attacks could succeed and still read "clean".
# An invariant that does not observe its own sentinels asserts nothing. (codex + grok, r9.)
GPAY="$GV/.payload"; GCAN="$GV/CANARY"; GOUT="$GV/WROTE"
printf '#!/bin/sh\ntouch "%s"\n' "$GCAN" > "$GPAY"; chmod +x "$GPAY"
rm -f "$GCAN" "$GOUT"
# CONTENT hashes, not a path listing: rewriting an existing file — .git/index is the one
# that matters for "reads do not write" — changes no path and was invisible before.
# The payload itself is excluded so its own presence is not mistaken for a change.
# PATH-FIRST records so LC_ALL=C sort and comm agree on ordering — hash-first records are
# ordered by hash, which is not the order comm requires and made the comparison unreliable.
gs_files() {
  # ONE shasum process for the whole tree, not one per file plus a `cut`: measured 409ms -> 22ms
  # per call on a 27-file fixture, and this is called from ten sites. `-exec ... +` batches AND —
  # unlike `xargs` — runs nothing at all on an empty tree, so shasum can never be left reading
  # stdin and hanging the suite. Output stays PATH-FIRST and LC_ALL=C sorted (see below);
  # verified byte-identical to the per-file form, including paths containing spaces.
  find "$GV" -type f ! -name '.payload' -exec shasum {} + 2>/dev/null \
    | sed -E 's/^([0-9a-f]+)  (.*)$/\2\t\1/' \
    | LC_ALL=C sort
}
# Any difference IN EITHER DIRECTION. `comm -13` alone missed deletions, so a review turn that
# removed a file read as clean. (codex, round 10.)
gs_changed() {  # <before> — prints a summary of what moved, empty if nothing did
  diff <(printf '%s\n' "$1") <(gs_files) 2>/dev/null | sed -n 's/^[<>] //p' | cut -f1 | sort -u
}
REAL_GIT="$(command -v git)"
# An ssh remote, so GIT_SSH_COMMAND / core.sshCommand have something to reach for. Without it
# git fails before touching ssh and the control cannot leak. The host is .invalid (RFC 2606):
# nothing resolves, so nothing leaves the machine.
git -C "$GV" remote add origin "ssh://git@nonexistent.invalid/x.git" >/dev/null 2>&1
# A LOCAL bare repo as a second remote. --upload-pack is only honoured for a local transport,
# so an ssh remote that never resolves cannot demonstrate the exec; against this one it does.
GV_PEER="$WORK/gitshim-peer"; git init -q --bare "$GV_PEER" >/dev/null 2>&1
# The baseline is deliberately DIRTY. A clean tree makes `git diff HEAD` empty, so an external
# diff driver is never invoked and the control cannot leak — which is precisely how fourteen
# cases came to "pass" while proving nothing. (grok, round 9: it reproduces on a dirty tree.)
gs_restore() {
  ( cd "$GV" && git checkout -- . >/dev/null 2>&1 || true )
  printf 'dirty\n' > "$GV/f.txt"
  rm -f "$GCAN" "$GOUT"
}
GS_BEFORE="$(gs_files)"
# EVERY case carries a NEGATIVE CONTROL. Round 9 replaced a blind harness with one that could
# see, and round 10 showed that was still not enough: several attacks produced no mutation even
# with the shim REMOVED, so "clean with the shim" proved nothing about the shim. Each case now
# runs twice — once against real git with no shim, which MUST leak, and once through the shim,
# which must not. A case whose control does not leak is reported as unproven, loudly, instead of
# counting as protection. (codex, round 10.)
gs_case() {  # <label> <env-assignments...> -- <git args...>
  local label="$1"; shift
  local envs=() ; while [ "$1" != "--" ]; do envs+=("$1"); shift; done; shift

  gs_restore; local base; base="$(gs_files)"
  ( cd "$GV" && env "${envs[@]}" "$REAL_GIT" "$@" ) >/dev/null 2>&1 || true
  local control; control="$(gs_changed "$base")"
  gs_restore

  base="$(gs_files)"
  ( cd "$GV" && env "${envs[@]}" "$GS/git" "$@" ) >/dev/null 2>&1 || true
  local shielded; shielded="$(gs_changed "$base")"
  gs_restore; GS_BEFORE="$(gs_files)"

  if [ -z "$control" ]; then
    fail "UNPROVEN: '$label' does not leak even without the shim — this case cannot detect a regression"
  elif [ -n "$shielded" ]; then
    fail "shim let a review turn $label (changed: $(printf '%s' "$shielded" | head -2 | tr '\n' ' '))"
  else
    ok "a review turn cannot $label (control leaks without the shim)"
  fi
}
# Prove the harness can SEE a violation. A test that cannot fail is not evidence, and this
# whole block previously could not fail for eight of its cases.
touch "$GV/harness-selftest"
if [ -n "$(gs_changed "$GS_BEFORE")" ]; then
  ok "the shim harness detects a new file (it can fail)"
else
  fail "the shim harness is blind to new files — every result below is vacuous"
fi
rm -f "$GV/harness-selftest"
printf 'mutate\n' >> "$GV/f.txt" 2>/dev/null || true
if [ -n "$(gs_changed "$GS_BEFORE")" ]; then
  ok "the shim harness detects an in-place rewrite"
else
  fail "the shim harness is blind to content changes"
fi
gs_restore; GS_BEFORE="$(gs_files)"
rm -f "$GV/f.txt"
if [ -n "$(gs_changed "$GS_BEFORE")" ]; then
  ok "the shim harness detects a DELETION (comm -13 could not)"
else
  fail "the shim harness is blind to deletions"
fi
gs_restore; GS_BEFORE="$(gs_files)"
gs_case "exec a program via GIT_EXTERNAL_DIFF" "GIT_EXTERNAL_DIFF=$GPAY" -- diff --ext-diff HEAD
gs_case "exec a program via GIT_SSH_COMMAND"  "GIT_SSH_COMMAND=$GPAY"  -- ls-remote origin
# REMOVED (unprovable here): GIT_PAGER / -p: git skips the pager entirely when stdout is not a TTY.
# The shim still refuses/neutralises it; we simply cannot demonstrate the leak in a
# non-interactive test, and a case that cannot fail must not be counted as coverage.
gs_case "inject config via GIT_CONFIG_*"      "GIT_CONFIG_COUNT=1" "GIT_CONFIG_KEY_0=diff.external" "GIT_CONFIG_VALUE_0=$GPAY" -- diff HEAD
gs_case "inject config via -c alias (the original bypass)" "X=1" -- -c "alias.ship=!$GPAY" ship
gs_case "inject config via -c core.sshCommand" "X=1" -- -c "core.sshCommand=$GPAY" ls-remote origin
gs_case "write a file via --output"           "X=1" -- log "--output=$GOUT"
# REMOVED (unprovable here): grep -O: same TTY dependency as the pager.
# The shim still refuses/neutralises it; we simply cannot demonstrate the leak in a
# non-interactive test, and a case that cannot fail must not be counted as coverage.
gs_case "exec via --upload-pack"              "X=1" -- ls-remote "--upload-pack=$GPAY" "$GV_PEER"
gs_case "write trace output via GIT_TRACE2_EVENT" "GIT_TRACE2_EVENT=$GV/trace.json" -- status
gs_case "write trace output via GIT_TRACE"        "GIT_TRACE=$GV/trace2.txt"         -- log --oneline -1
# REMOVED (unprovable here): GIT_MAN_VIEWER: `git help` does not exec the viewer in this environment.
# The shim still refuses/neutralises it; we simply cannot demonstrate the leak in a
# non-interactive test, and a case that cannot fail must not be counted as coverage.
# REMOVED (unprovable here): unlocked index write: `git status` does not rewrite .git/index here.
# The shim still refuses/neutralises it; we simply cannot demonstrate the leak in a
# non-interactive test, and a case that cannot fail must not be counted as coverage.
# Repo-LOCAL config is the case env-scrubbing can never cover: .git/config is a file, not a
# variable, and unsetting GIT_CONFIG_GLOBAL merely restores the default lookup. Re-baseline
# after writing the config, or the setup write is mistaken for the attack. (codex, round 9.)
git -C "$GV" config diff.external "$GPAY" >/dev/null 2>&1
git -C "$GV" config core.fsmonitor "$GPAY" >/dev/null 2>&1
GS_BEFORE="$(gs_files)"
gs_case "exec via repo-local diff.external config" "X=1" -- diff HEAD
gs_case "exec via repo-local core.fsmonitor config" "X=1" -- status
# -p AFTER the verb is --patch (log/diff) or --porcelain (blame) — the reviewer's own tools.
# Refusing it everywhere broke `git log -p` and the refusal text was false for that case.
( cd "$GV" && "$GS/git" log -p -1 ) >/dev/null 2>&1 \
  && ok "git log -p still works: after the verb -p is --patch, not --paginate" || fail "shim broke git log -p"
case "$( ( cd "$GV" && "$GS/git" -p log ) 2>&1 | head -1 )" in
  *"agent-comms: refused"*) ok "a LEADING -p (--paginate) is still refused" ;;
  *) fail "leading -p reached git" ;;
esac
git -C "$GV" config --unset diff.external >/dev/null 2>&1
git -C "$GV" config --unset core.fsmonitor >/dev/null 2>&1
GS_BEFORE="$(gs_files)"

gs() { PATH="$GS:$PATH" git "$@"; }
# A DENYLIST of subcommands cannot hold: git is user-extensible, so an alias runs under a
# name no list contains, and publishing/rewriting verbs are not all spelled "push". Each of
# these was verified bypassable against the previous denylist shim. (codex, round 6.)
gs_refused() {  # <label> <args...> — the shim must refuse, and real git must never run
  local label="$1"; shift
  local out; out="$("$GS/git" "$@" 2>&1 | head -1)"
  case "$out" in
    *"agent-comms: refused"*) ok "shim refuses $label" ;;
    *) fail "shim ALLOWED $label (got: ${out:0:70})" ;;
  esac
}
gs_allowed() {  # <label> <args...> — a read-only verb must reach the REAL git
  # Asserted as "not refused", not as a fixed output string: the shim now runs real git, so
  # the output is whatever the repo says. Pinning an exact string here is what let the old
  # echo-stub fixture pass while the shipped shim was defeatable.
  local label="$1"; shift
  local out; out="$("$GS/git" "$@" 2>&1 | head -1)"
  case "$out" in
    *"agent-comms: refused"*) fail "shim BLOCKED read-only $label (got: ${out:0:70})" ;;
    *) ok "shim passes $label through to git" ;;
  esac
}
GS_PUSH="pu""sh"; GS_COMMIT="co""mmit"
gs_refused "a shell alias defined inline (-c alias.X=!...)" -c "alias.ship=!git $GS_PUSH origin main" ship
gs_refused "send-pack, which publishes without saying push" send-pack origin main
gs_refused "tag -f, which rewrites a ref" tag -f v1
gs_refused "an --exec-path= that redirects git helpers" --exec-path=/tmp version
gs_refused "update-ref" update-ref refs/heads/main HEAD
gs_refused "the plain publishing verb" "$GS_PUSH" origin main
gs_refused "the plain writing verb" "$GS_COMMIT" -m x
gs_refused "a publishing verb behind a value-taking global" -C /tmp "$GS_PUSH"
gs_refused "an unknown verb (allowlist default-denies)" some-future-subcommand
gs_allowed "log"        log --oneline -1
gs_allowed "status"     status --short
gs_allowed "rev-parse"  rev-parse HEAD
gs_allowed "cat-file"   cat-file -t HEAD
gs_allowed "a read behind -C" -C . log --oneline -1
gs log --oneline -1 >/dev/null 2>&1 && ok "a review turn can still read git history" || fail "shim blocks git log"
gs diff --stat >/dev/null 2>&1 && ok "a review turn can still read the diff" || fail "shim blocks git diff"
gs show HEAD --stat >/dev/null 2>&1 && ok "a review turn can still read a commit" || fail "shim blocks git show"
check_not "a review turn cannot push" gs push origin main
check_not "a review turn cannot commit" gs commit -m x
check_not "a review turn cannot reset" gs reset --hard HEAD
check_not "a review turn cannot rewrite refs" gs update-ref refs/heads/x HEAD
# GLOBAL-OPTION BYPASS: -C/-c take a VALUE, and the old first-non-option break treated
# that value as the subcommand — `git -C . push` sailed straight through the refusal
# list. The scan must find the real subcommand past value-taking globals. (codex, panel r4.)
check_not "a review turn cannot push behind -C" gs -C . push origin main
check_not "a review turn cannot reset behind -c" gs -c user.name=x reset --hard HEAD
gs -C . log --oneline -1 >/dev/null 2>&1 \
  && ok "value-taking globals still work for reads (-C . log)" || fail "shim broke -C reads"
# No drift canary is needed any more: the fixture above IS the production generator, so
# there are no longer two shapes to keep in sync. What IS worth asserting is that the shim
# default-denies — an allowlist that falls through to exec on an unrecognised verb is a
# denylist wearing a costume, and that distinction is the whole security property here.
# (Removed: a grep for the refusal comment in runphase.sh. The unknown-verb case below
# refuses through the GENERATED shim, which is the property, not the prose.)
[ "$("$GS/git" definitely-not-a-real-verb 2>&1 | grep -c 'agent-comms: refused')" = "1" ] \
  && ok "an unrecognised verb is refused, not executed" || fail "shim fell through on an unknown verb"
# and the shim must not recurse into itself
# Asserted against the GENERATED shim, not the generator: what ships is this file, and an
# exec target that resolved through PATH would find the shim again and spin forever.
GS_EXEC="$(sed -n 's/^ *exec \(\/[^ ]*\).*/\1/p' "$GS/git" | head -1)"
[ -n "$GS_EXEC" ] && [ "$GS_EXEC" != "$GS/git" ] && [ -x "$GS_EXEC" ] \
  && ok "the shim execs the REAL git by absolute path, never itself" \
  || fail "shim exec target is not an absolute non-self path (got: ${GS_EXEC:-<none>})"
# The shim is worthless if it never reaches the child, and that wiring used to be asserted
# by grepping runphase.sh for a literal PATH= expression — a string match that would have
# stayed green through any refactor that dropped the export. Run a REAL mounted ACP turn
# and let the child report what it actually resolves `git` to. (codex, round 10.)
SW_ART="$(git -C "$MA_FIX" rev-parse HEAD 2>/dev/null)"
SW_MSG="$MA_FIX/.comms/to-grok/${MA_WS}_2026-08-20T09-58-00_shimpath-1.md"
{ head -1 "$MA_FIX/.comms/archive/$(basename "$MA_MSG")"
  printf 'artifact_id: %s\nhead_sha: %s\n' "$SW_ART" "$SW_ART"
  tail -n +2 "$MA_FIX/.comms/archive/$(basename "$MA_MSG")" | sed -e 's/^thread: ma-arc-1$/thread: ma-arc-shimpath/'
} > "$SW_MSG"
SW_DIR="$WORK/ma-shimpath"; mkdir -p "$SW_DIR"
printf 'x\n' > "$AXD/payload"
rm -f "$AXD/childenv"
# Mount lifecycle again, as grok, so it opts out of the containment refusal explicitly — see
# the note on wm_turn. The shim is DEFENCE IN DEPTH under an isolation backend, and it is what
# an operator who sets the override is left with, so it must keep working in exactly this case.
( cd "$MA_FIX" && env PATH="$AXB:$PATH" ACP_PARITY_PAYLOAD="$AXD/payload" \
    ACP_PARITY_PROBE="$AXD/childenv" COMMS_RUNPHASE_SPAWN_DELAY_SECS=0 \
    COMMS_RUNPHASE_ALLOW_UNCONTAINED=1 \
    "$RP" run --message "$SW_MSG" --dir "$SW_DIR" --provider grok --via acp --timeout-secs 20 ) \
  >/dev/null 2>&1
if [ ! -s "$AXD/childenv" ]; then
  fail "the mounted ACP child never ran — the PATH check would be vacuous"
elif grep -q "^git=$SW_DIR/shim/git\$" "$AXD/childenv"; then
  ok "a mounted child resolves git to the shim (it is really on the child PATH)"
else
  fail "a mounted child resolves git elsewhere (got: $(grep '^git=' "$AXD/childenv" | head -1))"
fi
