#!/bin/bash
# agent-comms verify v1
#
# ci/verify.sh — the committed suite `comms.sh integrate` runs (suite-cmd = bash ci/verify.sh).
# Generated by `comms.sh verify init` from agent-comms' helpers/verify.sh. Refresh it with
# `comms.sh verify init --update`, which replaces this file only and keeps ci/verify.steps.
#
# integrate runs the suite in a FRESH checkout of the candidate: tracked files only, no installed
# dependencies, no shell around suite-cmd. This script therefore does two things, in order:
#
#   1. PROVISION  detect the stack by lockfile at the repo root and run a FROZEN install, which never
#                 rewrites a lockfile. The package managers keep their caches outside the checkout.
#                   package-lock.json      npm ci --no-audit --no-fund
#                   pnpm-lock.yaml         pnpm install --frozen-lockfile   (corepack when pinned)
#                   yarn.lock              yarn install --immutable (berry) / --frozen-lockfile
#                   bun.lock / bun.lockb   bun install --frozen-lockfile    (one stack)
#                   uv.lock                uv sync --frozen
#                   requirements.txt       python3 -m venv .venv + .venv/bin/pip install -r
#                                          (NEVER when there is a uv.lock, even if named in a
#                                          directive: uv.lock wins, pip must not overwrite its .venv;
#                                          an `-e .` line also writes *.egg-info: gitignore it)
#                   Cargo.lock             cargo fetch --locked
#                   go.sum                 go mod download
#                   mix.lock               mix deps.get --check-locked
#                 Every directory an install creates must be gitignored, or integrate would refuse
#                 the run as dirt; that is checked BEFORE installing, with a message naming the line
#                 to add. More than one JavaScript lockfile at the root is a conflict: choose one.
#
#   2. CHECK      run ci/verify.steps: one shell command per line; blank lines and `#` comments
#                 (indented ones too) are ignored. Each step runs as `bash -euo pipefail -c "<line>"` with stdin closed, stops
#                 the suite on failure, and is named in the error. Without a steps file, detected
#                 defaults run (package.json `check`+`test`, else `lint`/`typecheck`/`test`; pytest;
#                 cargo test --locked; go test -mod=readonly ./...; mix test).
#
# Directive, in ci/verify.steps:   #@ provision: none          skip provisioning entirely
#                                  #@ provision: pnpm,uv        provision exactly these stacks
#                                  (at most one JavaScript manager, and never pip together with uv:
#                                  each pair would install into the same directory)
#
# KNOWN LIMIT: `false; true` and `false | cat` fail correctly, but a failure the line itself
# handles (`false || true`), a failing member of a conditional list (`false && true; true`), and
# anything inside a nested shell (`sh -c 'false; true'`) cannot be seen. Write each step as one
# simple command or call a repo script. The steps `verify init` generates are always simple.
#
# Zero steps is a FAILURE, never a pass: a suite that checks nothing is the unverified landing
# integrate exists to refuse.
#
# Modes:  bash ci/verify.sh              provision, then run every step
#         bash ci/verify.sh --plan       print what would run and the ignore status; run nothing
#         bash ci/verify.sh --emit-steps print the detected default steps, one per line
set -euo pipefail

MODE=run
case "${1:-}" in
  "") ;;
  --plan) MODE=plan ;;
  --emit-steps) MODE=emit ;;
  *) printf 'verify: unknown argument %s (expected --plan or --emit-steps)\n' "$1" >&2; exit 2 ;;
esac

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { printf 'verify: not inside a git repository\n' >&2; exit 1; }
cd "$ROOT"
STEPS_FILE="ci/verify.steps"
export CI=true

# Banners start with `==` so no line of ours can ever look like the `passed: N  failed: N  skipped: N`
# completion line integrate takes as proof in repos that carry tests/expected-counts.tsv.
say()  { printf '== verify: %s\n' "$*"; }
fail() { printf 'verify: %s\n' "$*" >&2; exit 1; }

# ---- which stacks -------------------------------------------------------------------------------
PROVISION=auto
if [ -f "$STEPS_FILE" ]; then
  PROVISION_LINE="$(sed -n 's/^[[:space:]]*#@[[:space:]]*provision:[[:space:]]*//p' "$STEPS_FILE" | tail -1 | tr -d '\r')"
  [ -z "$PROVISION_LINE" ] || PROVISION="$PROVISION_LINE"
fi

STACKS=""
add_stack() { case " $STACKS " in *" $1 "*) ;; *) STACKS="${STACKS:+$STACKS }$1" ;; esac; }
if [ "$PROVISION" = auto ]; then
  js="" js_n=0 js_files=""
  if [ -f package-lock.json ]; then js=npm; js_n=$((js_n + 1)); js_files="$js_files package-lock.json"; fi
  if [ -f pnpm-lock.yaml ]; then js=pnpm; js_n=$((js_n + 1)); js_files="$js_files pnpm-lock.yaml"; fi
  if [ -f yarn.lock ]; then js=yarn; js_n=$((js_n + 1)); js_files="$js_files yarn.lock"; fi
  if [ -f bun.lock ] || [ -f bun.lockb ]; then js=bun; js_n=$((js_n + 1)); js_files="$js_files bun.lock(b)"; fi
  [ "$js_n" -le 1 ] || fail "more than one JavaScript lockfile at the root:$js_files — choose one with a '#@ provision: <npm|pnpm|yarn|bun>' line in $STEPS_FILE"
  [ -z "$js" ] || add_stack "$js"
  if [ -f uv.lock ]; then add_stack uv; elif [ -f requirements.txt ]; then add_stack pip; fi
  [ ! -f Cargo.lock ] || add_stack cargo
  [ ! -f go.sum ] || add_stack go
  [ ! -f mix.lock ] || add_stack mix
elif [ "$PROVISION" != none ]; then
  for s in $(printf '%s' "$PROVISION" | tr ',' ' '); do
    case "$s" in
      pip|requirements)
        [ ! -f uv.lock ] || fail "'#@ provision: $s' is refused while uv.lock exists — uv.lock wins, and pip over uv's .venv could verify a different resolution"
        add_stack pip ;;
      npm|pnpm|yarn|bun|uv|cargo|go|mix) add_stack "$s" ;;
      *) fail "unknown stack '$s' in '#@ provision:' (known: npm pnpm yarn bun uv pip|requirements cargo go mix none)" ;;
    esac
  done
  # A directive picks stacks by name, so it must not recreate the collisions auto-detection
  # refuses: two JavaScript managers share node_modules, and pip and uv share .venv.
  js_named=""
  for s in $STACKS; do case "$s" in npm|pnpm|yarn|bun) js_named="$js_named $s" ;; esac; done
  [ "$(printf '%s' "$js_named" | wc -w | tr -d ' ')" -le 1 ] \
    || fail "'#@ provision:' names more than one JavaScript manager:$js_named — they would install into the same node_modules; name one"
  case " $STACKS " in *" pip "*) case " $STACKS " in *" uv "*)
    fail "'#@ provision:' names both pip and uv — they would install into the same .venv; name one" ;; esac ;; esac
fi

# ---- package manager invocations ----------------------------------------------------------------
pinned_by() {  # <tool> — 0 when package.json's packageManager field pins this tool
  [ -f package.json ] && grep -Eq "\"packageManager\"[[:space:]]*:[[:space:]]*\"$1@" package.json
}
yarn_berry() { [ -f .yarnrc.yml ]; }
yarn_linker() {  # prints node-modules | pnp | pnpm for berry; classic always uses node_modules
  local l
  l="$(sed -n 's/^nodeLinker:[[:space:]]*"\{0,1\}\([a-z-]*\)"\{0,1\}.*/\1/p' .yarnrc.yml 2>/dev/null | head -1)"
  printf '%s' "${l:-pnp}"
}
js_runner() {  # <stack> — the command prefix that runs a package.json script
  case "$1" in
    npm) printf 'npm run' ;;
    pnpm) if pinned_by pnpm && command -v corepack >/dev/null 2>&1; then printf 'corepack pnpm run'; else printf 'pnpm run'; fi ;;
    yarn) if pinned_by yarn && command -v corepack >/dev/null 2>&1; then printf 'corepack yarn run'; else printf 'yarn run'; fi ;;
    bun) printf 'bun run' ;;
  esac
}
provision_cmd() {  # <stack> — the frozen install command
  case "$1" in
    npm) printf 'npm ci --no-audit --no-fund' ;;
    pnpm) if pinned_by pnpm && command -v corepack >/dev/null 2>&1; then printf 'corepack pnpm install --frozen-lockfile'; else printf 'pnpm install --frozen-lockfile'; fi ;;
    yarn)
      local y=yarn
      if pinned_by yarn && command -v corepack >/dev/null 2>&1; then y='corepack yarn'; fi
      if yarn_berry; then printf '%s install --immutable' "$y"; else printf '%s install --frozen-lockfile' "$y"; fi ;;
    bun) printf 'bun install --frozen-lockfile' ;;
    uv) printf 'uv sync --frozen' ;;
    pip) printf 'python3 -m venv .venv && .venv/bin/pip install -r requirements.txt' ;;
    cargo) printf 'cargo fetch --locked' ;;
    go) printf 'go mod download' ;;
    mix) printf 'mix deps.get --check-locked' ;;
  esac
}
tool_of() {  # <stack> — the binary that must be on PATH
  case "$1" in
    npm) printf npm ;; pnpm) pinned_by pnpm && command -v corepack >/dev/null 2>&1 && printf corepack || printf pnpm ;;
    yarn) pinned_by yarn && command -v corepack >/dev/null 2>&1 && printf corepack || printf yarn ;;
    bun) printf bun ;; uv) printf uv ;; pip) printf python3 ;; cargo) printf cargo ;; go) printf go ;; mix) printf mix ;;
  esac
}
outputs_of() {  # <stack> — the UNTRACKED paths its install creates; a trailing slash marks a directory
  case "$1" in
    npm|pnpm|bun) printf 'node_modules/\n' ;;
    yarn)
      if yarn_berry && [ "$(yarn_linker)" = pnp ]; then
        printf '.pnp.cjs\n.yarn/install-state.gz\n'
        grep -Eq '^pnpEnableEsmLoader:[[:space:]]*true' .yarnrc.yml 2>/dev/null && printf '.pnp.loader.mjs\n'
      else
        printf 'node_modules/\n'
      fi ;;
    uv|pip) printf '.venv/\n' ;;
    cargo) printf 'target/\n' ;;
    go) ;;
    mix) printf 'deps/\n_build/\n' ;;
  esac
}

# ---- ignore preflight (directory-aware) ---------------------------------------------------------
# `git check-ignore node_modules` answers "no" against the usual `node_modules/` rule while the
# directory does not exist yet, which is exactly the fresh checkout; asking about `node_modules/`
# (trailing slash) answers correctly. A TRACKED output (a Yarn zero-install `.pnp.cjs`) is allowed:
# if an install rewrites it, integrate's final cleanliness check refuses the run.
ignore_status() {  # <path> — prints ignored | tracked | NOT-IGNORED
  local p="$1"
  if git ls-files --error-unmatch -- "${p%/}" >/dev/null 2>&1; then printf tracked; return; fi
  if git check-ignore -q -- "$p" 2>/dev/null; then printf ignored; else printf NOT-IGNORED; fi
}

# ---- default checks -----------------------------------------------------------------------------
pkg_scripts() {  # the package.json script names, one per line
  [ -f package.json ] || return 0
  if command -v node >/dev/null 2>&1; then
    node -e 'const s=(require("./package.json").scripts)||{};for(const k of Object.keys(s))console.log(k)'
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json;[print(k) for k in (json.load(open("package.json")).get("scripts") or {})]'
  else
    fail "cannot read package.json scripts (no node or python3 on PATH); list the checks in $STEPS_FILE"
  fi
}
has_pytest() {
  [ -d tests ] || [ -d test ] || [ -f pytest.ini ] || [ -f conftest.py ] \
    || { [ -f pyproject.toml ] && grep -q '^\[tool\.pytest' pyproject.toml; } \
    || { [ -f setup.cfg ] && grep -q '^\[tool:pytest\]' setup.cfg; }
}
default_steps() {
  local s scripts runner
  for s in $STACKS; do
    case "$s" in
      npm|pnpm|yarn|bun)
        scripts="$(pkg_scripts)" || exit 1
        runner="$(js_runner "$s")"
        if printf '%s\n' "$scripts" | grep -qx check; then
          printf '%s check\n' "$runner"
          printf '%s\n' "$scripts" | grep -qx test && printf '%s test\n' "$runner"
        else
          for n in lint typecheck test; do
            printf '%s\n' "$scripts" | grep -qx "$n" && printf '%s %s\n' "$runner" "$n"
          done
        fi ;;
      uv) has_pytest && printf 'uv run --frozen python -m pytest\n' ;;
      pip) has_pytest && printf '.venv/bin/python -m pytest\n' ;;
      cargo) printf 'cargo test --locked\n' ;;
      go) printf 'go test -mod=readonly ./...\n' ;;
      mix) printf 'mix test\n' ;;
    esac
  done
  return 0
}

STEPS=()
if [ -f "$STEPS_FILE" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%$'\r'}"
    # Leading blanks first: an INDENTED comment is still a comment. Counted as a step it would
    # run as an empty shell, pass, and let a file of comments satisfy the zero-steps gate.
    line="${line#"${line%%[![:space:]]*}"}"
    case "$line" in ''|\#*) continue ;; esac
    STEPS+=("$line")
  done < "$STEPS_FILE"
else
  DEFAULTS="$(default_steps)" || exit 1
  while IFS= read -r line; do [ -z "$line" ] || STEPS+=("$line"); done <<EOF
$DEFAULTS
EOF
fi

if [ "$MODE" = emit ]; then
  [ "${#STEPS[@]}" -gt 0 ] || exit 0
  printf '%s\n' "${STEPS[@]}"
  exit 0
fi

# ---- plan: say what would happen, run nothing ---------------------------------------------------
if [ "$MODE" = plan ]; then
  say "stacks: ${STACKS:-none} (provision: $PROVISION)"
  for s in $STACKS; do
    say "provision $s: $(provision_cmd "$s")"
    while IFS= read -r o; do [ -z "$o" ] || say "  output $o: $(ignore_status "$o")"; done <<EOF
$(outputs_of "$s")
EOF
  done
  if [ "${#STEPS[@]}" -eq 0 ]; then
    say "steps: NONE — add $STEPS_FILE (one command per line)"
    exit 1
  fi
  src="detected defaults"; [ ! -f "$STEPS_FILE" ] || src="$STEPS_FILE"
  say "steps (${#STEPS[@]}, from $src):"
  for st in "${STEPS[@]}"; do say "  $st"; done
  exit 0
fi

# ---- run ----------------------------------------------------------------------------------------
[ "${#STEPS[@]}" -gt 0 ] || fail "no checks found — add $STEPS_FILE with one command per line (a suite that checks nothing cannot verify a landing)"

for s in $STACKS; do
  t="$(tool_of "$s")"
  command -v "$t" >/dev/null 2>&1 || fail "stack '$s' needs '$t' on PATH"
  while IFS= read -r o; do
    [ -n "$o" ] || continue
    [ "$(ignore_status "$o")" != NOT-IGNORED ] \
      || fail "'$o' is not gitignored — the $s install would leave git-visible files and integrate would refuse the run. Add '$o' to .gitignore."
  done <<EOF
$(outputs_of "$s")
EOF
done

for s in $STACKS; do
  cmd="$(provision_cmd "$s")"
  say "provision $s: $cmd"
  set +e
  bash -euo pipefail -c "$cmd" </dev/null
  rc=$?
  set -e
  [ "$rc" = 0 ] || { printf 'verify: provisioning %s failed (exit %s): %s\n' "$s" "$rc" "$cmd" >&2; exit "$rc"; }
done

n=0
for st in "${STEPS[@]}"; do
  n=$((n + 1))
  say "step $n/${#STEPS[@]}: $st"
  set +e
  bash -euo pipefail -c "$st" </dev/null
  rc=$?
  set -e
  [ "$rc" = 0 ] || { printf 'verify: step %s/%s failed (exit %s): %s\n' "$n" "${#STEPS[@]}" "$rc" "$st" >&2; exit "$rc"; }
done
say "all ${#STEPS[@]} steps passed"
